# Generated by Django 5.0.6 on 2024-05-17 02:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('english_test', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='test',
            name='number_of_question',
        ),
    ]
