# Generated by Django 5.0.6 on 2024-05-20 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('english_test', '0003_test_number_of_words'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='topic',
            field=models.CharField(default='', max_length=50),
        ),
    ]
