# Generated by Django 5.0.6 on 2024-05-17 02:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('english_test', '0003_test_number_of_words'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dictionary',
            fields=[
                ('dict_id', models.AutoField(primary_key=True, serialize=False)),
                ('word', models.CharField(max_length=200)),
                ('meaning', models.CharField(max_length=200)),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='english_test.test')),
            ],
        ),
    ]
